apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter-crd
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  chart:
    spec:
      chart: karpenter-crd
      version: "1.14.1"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  dependsOn:
    - name: karpenter-crd
  chart:
    spec:
      chart: karpenter
      version: "1.14.1"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  values:
    settings:
      clusterName: ai-agent-cluster
      interruptionQueue: Karpenter-ai-agent-cluster
    serviceAccount:
      create: true
      name: karpenter
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: "ScheduleAnyway"
