apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-gp3.yaml
  - gateway-api-crds.yaml
  - inference-extension-crds.yaml
  - kaito-crds.yaml
  - cert-manager
  - traefik
  - karpenter
