apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: authelia
type: Opaque
stringData:
  # Internal encryption keys for test setup
  identity_validation.reset_password.jwt.hmac.key: "4xUsTohHPqQhPtfFeUBnFEIj9qYcET7PyV4GFYiWmdCrdMCpHwngaZLCCPIXLiZ4"
  session.encryption.key: "Qvl65kbqY36XBUtC7HcI5mttfR7bNerHHtkib2j8XSJwV0ZHHIW9ONvXEfBQ0IbY"
  storage.encryption.key: "dVxTwtvs62SB53fpsGIBn8QoSoZiDIdr7cNP4by0SrEi1GGDspWX5JlnlfRsLF2L"
  identity_providers.oidc.hmac.key: "6RJKTwrR9YhcmmJq8zoX1VG1IqV2Owpk8xSVMsfwwgpLmnpYd4pZOJp4QJsaWAKE"
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-oidc-key
  namespace: authelia
type: Opaque
stringData:
  oidc.rsa.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZB3T1inBshU2S
    yxN9Tz/dMl1xn/i3s+8h/JRF920XGVyN8wMNG3mmKbSisNkKy7US48Kd7Wjg7qP0
    5U2EG7hWWktCc9WlHwh8yRIK6iQJ76g6ELpPoSnCndmrmUWBJeCZb+wUSTRPvz0W
    KT+GP2WB6t58hqHOhnQft3u6CvV6GGcbW1XI2nGcCrXD1mgYf7yL3xKCR78aVuwH
    q+IE1k1vDhzH187YIL1RurSijLmjywBkDm+5qJrAE0HuqviHgs07ZtWyHC7DLn+e
    YBqrvMZg614qFChJm1isAun1tQXeeftM7C/TQYYQkdHF51iCJ4QMMt6Qs4iYeSfS
    V+WEANinAgMBAAECggEASpN9ZUKFD0VfOqn9sHmjAGdmJL1LwhRaf9tDOCelnOJi
    I4T173MZgjeikqUib8tAFZWeMpZ6C5D1VhnVYSgFV+b/JX6YU30udXLCeG2spJ1t
    uUY2P1ap+u4y9fxdHdveKduDzBS7nQuh+hOCeKcgQlxqx2+b+lPJY3yxT2SkpadK
    7cRCq+YYSUfAXrAlOJnX4GlK5szA+Min1CW5qsM7InNVO2rGR4t39qNYboFqWEwl
    div+68a7xja73bYVu1SXTNIYjrBJhvAFLTYOLDxHvjO8zrO9VZ4bBaRhonM5qOno
    whb2Km4y0cfQNZUmL4qZMslCqSHU3+eQ26F3G+hNwQKBgQD0Vpvecw7tC4DC7Wrk
    UiJ9UdEC8cHfERxeaTdczVexs4hvq9e7vbVieCdmK3Pqm+h7ACnAR2vUx9GRHQpg
    +O2S+mqukqSdTVoxvvmtxUQIrJ2lWB7tZWQ2Ag+rTEREf1Z7COfS8FJ60CbXBFlC
    DC9E8+CD438/ojzBuU7tyvPdiwKBgQDjYy1RgHAS/GUZO4p7N8dewf++zrsUFR+g
    qXyjle1O0ow6Q73ZmhTIxirTTz5bm1FncbMnw6gW2fHSDYkXCmsux3iub03S2x7U
    UMRrmd8BPtvUQbf7CQHta6l/4VBsqHzgnjvs1LKCHL0q/A90WZZLT5YLKqb8GL5B
    I6YVTwUM1QKBgEffii4fTk6wSYoNaJoNBxQyEvd4wfyp/dxPuvdTd+5Pz1x6AhW5
    sjdq/LvzID/s6K/11lI3MCMBPEYhcsIft1K60tLTVBTpghSMBsn08xRSInVWvJI8
    dwPkC1PqNVKo2nmKnxbPlpOF00cAgnkJOIZh7rMdIntHb/PUXMFaJ+4NAoGAIief
    gwJ70x4+QVAEOQXj2IPjWlHLH/UcTxGmOxwmDRTrI0VRmwHd5Vp+zEa24yOtUpBt
    jKeC9AvAmwCVevSBrQEhS3JEikuHkfSfzFnMeW9rrbJBZF+x/muRhjfd0LRuLX8X
    GTfJqGmQsIgz+hIK1T0bGIpLkspUqYwlQkYgSBECgYEAu4PQ6XmbguSezRIEvUlx
    FKZkxHa3g4FEXmfaIuRzTMvuVjBMyXueTWPf2jTb7jIEjp7aLlxcRUfVPBrxcIF9
    SBbz5decDBLS525YWDVv/koSMhOfXGEDGyKHEr4qxwQUBjfS1G2wMr75/4w82KHi
    Fj83Cg0vDZz4ekkdg6JAojQ=
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$RV/ZOBhzfrzJHhMFFV4Rmg$CinVuqWX+9h7coJE7b4xoKu5WarEsZfP1UaOYhs+T4A"
        email: "admin@example.com"
        groups:
          - admins
          - dev
      user:
        displayname: "Standard User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$owOTxRlipX8XoNJC3BBbXA$a3exrPUT1FTFsnjUUQ3+SIxOWcPmYvqx9YHbIZAopOs"
        email: "user@example.com"
        groups:
          - users
