apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-headers
  namespace: authelia
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authelia
  namespace: authelia
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - auth.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: authelia-headers
      backendRefs:
        - name: authelia-authelia
          port: 80
