apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
