apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemma
  namespace: kagent
spec:
  provider: OpenAI
  model: gemma
  openAI:
    baseUrl: "http://llm-d.llm-d.svc.cluster.local:8000/v1"
