apiVersion: v1
kind: Secret
metadata:
  name: gemma-apikey
  namespace: kagent
type: Opaque
stringData:
  # This is fake, of course, but it is used to demonstrate how to use a secret for the API key.
  api-key: "kaito-gateway"
